### ISSUE TITLE
Joining Guild with Private System Channel

### ISSUE THREAD

**Issue by MRegirouard** [MRegirouard/Mrs.Patterson-Bot#2]
**Describe the bug**
An obscure error prints when joining a guild with a private system channel.

**Steps To Reproduce**
1. Set system channel to private (I think -- I simply turned off all permissions except "Send Messages")
2. Add the bot to the guild
3. The bot will output the following error message

```
[ FAIL ] Error sending hello message to new gulid: DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/pi/Share/DiscordBots/Mrs.Patterson Bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/home/pi/Share/DiscordBots/Mrs.Patterson-Bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/868869738162454558/messages',
  code: 50001,
  httpStatus: 403
 }
```

**Expected behavior**
An intentional and more clear error message should print rather than this obscure generated one. Full access checks should be performed before attempting to post a welcome message.

**Node.js Version**
`v14.15.1`

**Mrs.Patterson-Bot Version**
- [x] I am on the latest `main` branch version
Commit hash: `a94494e90e6157b971122acc56e84ded5b0b7b4f`

**Comment by MRegirouard** [comment]
It appears the bot needs the `View Channel`, `Send Messages`, and `Embed Links` permissions to send the welcome embed.

Perhaps in the future, we can add a special case if the `Embed Links` permission is missing, and send a standard message instead of the detailed embed. Also, if the system channel doesn't exist or the bot doesn't have the `View Channel` and `Send Messages` permissions, it can find a different channel to post the welcome in. However, we must consider etiquette and ensure the bot doesn't post where it shouldn't.
